# Generated by Django 3.1.1 on 2020-09-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
